extends: [ '@commitlint/config-conventional' ]
parserPreset: 'conventional-changelog-conventionalcommits'
formatter: '@commitlint/format'
rules: {
  subject-case: [ 2, 'always', ['lower-case', 'upper-case', 'sentence-case', 'start-case'] ]
}
defaultIgnores: true
helpUrl: 'https://github.com/conventional-changelog/commitlint/#what-is-commitlint'
