name: Build Proxmox LXC Container Template
on:
  workflow_dispatch:

jobs:
  build-lxc-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Generate NixOS configuration
        run: |
          nix run github:nix-community/nixos-generators -- -f proxmox-lxc --flake .#default | {
            read path
            echo "BUILD_PATH=$path" >> $GITHUB_ENV
          }
